import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";
import { prisma } from "@/src/lib/prisma";
import { getActiveUser } from "@/src/lib/session";
import { RoleSwitcher } from "@/src/components/role-switcher";
import { ROLE_LABELS } from "@/src/types/itil";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// This layout is now `async` — layouts and pages are allowed to be async
// functions in the App Router, and `await`-ing here is what lets us read
// the database and the request's cookies before the HTML is built, on
// every request (the root page below already opted the app into dynamic
// rendering, which is what makes "every request" true here too).
export default async function RootLayout({ children }: LayoutProps<"/">) {
  const [users, activeUser] = await Promise.all([
    prisma.user.findMany({ orderBy: { name: "asc" } }),
    getActiveUser(),
  ]);

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <header className="flex items-center justify-between border-b border-black/10 px-6 py-3 dark:border-white/10">
          <Link href="/" className="font-semibold text-black dark:text-zinc-50">
            ITIL Service Desk
          </Link>
          <div className="flex items-center gap-4">
            <Link
              href="/incidents"
              className="text-sm text-zinc-600 hover:text-black dark:text-zinc-400 dark:hover:text-zinc-50"
            >
              Search
            </Link>
            {activeUser && (
              <span className="text-xs text-zinc-500 dark:text-zinc-400">
                {ROLE_LABELS[activeUser.role]}
              </span>
            )}
            <RoleSwitcher users={users} activeUserId={activeUser?.id ?? null} />
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
