import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";
import { prisma } from "@/src/lib/prisma";
import { getActiveUser } from "@/src/lib/session";
import { logout } from "@/src/actions/auth";
import { ROLE_LABELS, isAgentRole } from "@/src/types/itil";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// This layout is now `async` — layouts and pages are allowed to be async
// functions in the App Router, and `await`-ing here is what lets us read
// the request's session cookie before the HTML is built, on every
// request (the root page below already opted the app into dynamic
// rendering, which is what makes "every request" true here too).
export default async function RootLayout({ children }: LayoutProps<"/">) {
  const activeUser = await getActiveUser();
  const unreadCount = activeUser
    ? await prisma.notification.count({ where: { recipientId: activeUser.id, read: false } })
    : 0;

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <header className="flex items-center justify-between border-b border-black/10 px-6 py-3 dark:border-white/10">
          <Link href="/" className="font-semibold text-black dark:text-zinc-50">
            ITIL Service Desk
          </Link>
          <div className="flex items-center gap-4">
            <Link
              href="/incidents"
              className="text-sm text-zinc-600 hover:text-black dark:text-zinc-400 dark:hover:text-zinc-50"
            >
              Search
            </Link>
            {activeUser && isAgentRole(activeUser.role) && (
              <Link
                href="/problems"
                className="text-sm text-zinc-600 hover:text-black dark:text-zinc-400 dark:hover:text-zinc-50"
              >
                Problems
              </Link>
            )}
            {activeUser && isAgentRole(activeUser.role) && (
              <Link
                href="/changes"
                className="text-sm text-zinc-600 hover:text-black dark:text-zinc-400 dark:hover:text-zinc-50"
              >
                Changes
              </Link>
            )}
            <Link
              href="/training"
              className="text-sm text-zinc-600 hover:text-black dark:text-zinc-400 dark:hover:text-zinc-50"
            >
              Training
            </Link>
            {activeUser && (
              <Link
                href="/inbox"
                className="flex items-center gap-1.5 text-sm text-zinc-600 hover:text-black dark:text-zinc-400 dark:hover:text-zinc-50"
              >
                Inbox
                {unreadCount > 0 && (
                  <span className="rounded-full bg-red-600 px-1.5 py-0.5 text-xs font-medium text-white">
                    {unreadCount}
                  </span>
                )}
              </Link>
            )}
            {activeUser ? (
              <>
                <span className="text-xs text-zinc-500 dark:text-zinc-400">
                  {activeUser.name} — {ROLE_LABELS[activeUser.role]}
                </span>
                <form action={logout}>
                  <button
                    type="submit"
                    className="text-sm text-zinc-600 hover:text-black dark:text-zinc-400 dark:hover:text-zinc-50"
                  >
                    Sign out
                  </button>
                </form>
              </>
            ) : (
              <Link
                href="/login"
                className="rounded-full bg-foreground px-4 py-1.5 text-sm font-medium text-background transition-colors hover:bg-[#383838] dark:hover:bg-[#ccc]"
              >
                Sign in
              </Link>
            )}
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
